defaults:
  - _self_

# experiment
experiment: bc

agent:
  _target_: bcagent.BCAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  max_action: ???
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3