defaults:
  - _self_

# experiment
experiment: cql

agent:
  _target_: cql.CQLAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  max_action: ???
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  offline: ${offline}
  cql_importance_sample: ${cql_importance_sample}
  temp: ${temp}
  min_q_weight: ${min_q_weight}
  num_random: ${num_random}
  with_lagrange: ${with_lagrange}
  lagrange_thresh: ${lagrange_thresh}
